import numpy as np
import control as ct

from Models.base import BaseLinearStateSpaceModel, BaseNonlinearModel
from Metrics_Plotting.SimLog import SimLog


class TFSimulator:
    """Simulates a discrete transfer function step-by-step using its difference equation.

    Given a transfer function B(z)/A(z), each call to ``step`` advances the recursion:
        a0·y[k] = b0·u[k] + b1·u[k-1] + … − a1·y[k-1] − a2·y[k-2] − …

    """

    def __init__(self, tf, X_0):
        """Initialises the simulator from a discrete transfer function.

        Args:
            tf (ct.TransferFunction): Discrete transfer function generated by python-control.
            X_0 (float): Initial output value (currently used only to set the concept of an
                initial condition; internal histories are zeroed regardless).
        """
        self.num_dis = np.asarray(tf.num_list[0][0], dtype=float)
        self.den_dis = np.asarray(tf.den_list[0][0], dtype=float)

        self.u_hist = np.zeros(len(self.num_dis))

        if len(self.den_dis) > 1:
            self.y_hist = np.zeros(len(self.den_dis) - 1)
        else:
            self.y_hist = np.array([])

    def reset(self, X_0):
        """Resets the input and output history buffers to zero.

        Call this before starting a new simulation run to avoid carry-over from
        a previous run.

        Args:
            X_0 (float): Unused; kept for interface consistency with the runner functions.
        """
        self.u_hist = np.zeros(len(self.num_dis))
        if len(self.den_dis) > 1:
            self.y_hist = np.zeros(len(self.den_dis) - 1)
        else:
            self.y_hist = np.array([])

    def step(self, u):
        """Advances the difference equation by one sample and returns the new output y[k].

        Implements:
            y[k] = (b0·u[k] + b1·u[k-1] + … − a1·y[k-1] − …) / a0

        Args:
            u (float): Current input sample u[k].

        Returns:
            float: Current output sample y[k].
        """
        self.u_hist[1:] = self.u_hist[:-1]
        self.u_hist[0] = float(u)

        y = np.dot(self.num_dis, self.u_hist)       # b0·u[k] + b1·u[k-1] + …
        y -= np.dot(self.den_dis[1:], self.y_hist)  # − a1·y[k-1] − a2·y[k-2] − …
        y /= self.den_dis[0]                         # divide by leading denominator coefficient a0

        if len(self.y_hist) > 0:
            self.y_hist[1:] = self.y_hist[:-1]
            self.y_hist[0] = y

        return y


class HybridSim:
    """Hybrid simulator: continuous linear plant (state-space) driven by a discrete controller.

    The plant is integrated at a fine timestep ``dt_plant`` = 1 ms (1 kHz) using fourth-order
    Runge-Kutta (RK4), while the controller output is updated at the coarser ``config_file.dt``
    (typically 20 ms / 50 Hz).  This ratio gives 20 RK4 substeps per control period, which is
    enough to make the integration error negligible compared with sampling effects.
    """

    def __init__(self, StateSpaceModel: BaseLinearStateSpaceModel, config_file):
        """Initialises the hybrid simulator with a linear continuous plant.

        Args:
            StateSpaceModel (LinearStateSpaceModel): Provides the continuous A, B, C matrices
                of the linearised plant.
            config_file: Plant configuration module; must expose ``T`` (total simulation time [s])
                and ``dt`` (controller sampling period [s]).
        """
        # Integration step for the continuous plant.
        # 1 ms (1 kHz) is 20× finer than the 50 Hz controller period, keeping RK4 truncation
        # error well below the quantisation effects introduced by the discrete controller.
        self.dt_plant = 1e-3

        self.A = StateSpaceModel.A.astype(float)
        self.B = StateSpaceModel.B.astype(float)
        self.C = StateSpaceModel.C.astype(float)
        self.config_file = config_file

    def rk4_step(self, X, u_k):
        """Advances the continuous state one integration step using classical RK4.

        Integrates  Ẋ = A·X + B·u  over one ``dt_plant`` interval with the control
        input u_k held constant (zero-order hold within the substep).

        Args:
            X (np.ndarray): Current state vector X[k], shape (n, 1).
            u_k (np.ndarray): Control input applied during this step, shape (m, 1).

        Returns:
            np.ndarray: Updated state vector X[k+1], shape (n, 1).
        """
        def f(X):
            return self.A @ X + self.B @ u_k

        k1 = f(X)
        k2 = f(X + self.dt_plant * 0.5 * k1)
        k3 = f(X + 0.5 * self.dt_plant * k2)
        k4 = f(X + self.dt_plant * k3)

        return X + self.dt_plant / 6 * (k1 + 2*k2 + 2*k3 + k4)


class NonLinearHybridSim:
    """Hybrid simulator: generic nonlinear plant driven by a discrete controller.

    Identical structure to ``HybridSim`` but uses the nonlinear ODE ``f(X, u)`` from
    a ``BaseNonlinearModel`` subclass instead of linear state-space matrices.  The plant
    is integrated at ``dt_plant`` = 1 ms using RK4; the controller output is updated at
    the coarser ``config_file.dt``.  The output matrix C is read from the model.
    """

    def __init__(self, model: BaseNonlinearModel, config_file):
        """Initialises the nonlinear hybrid simulator.

        Args:
            model (BaseNonlinearModel): Nonlinear plant model; its ``f`` method is used
                as the ODE right-hand side and its ``C`` attribute as the output matrix.
            config_file: Plant configuration module; must expose ``T`` (total simulation time [s])
                and ``dt`` (controller sampling period [s]).
        """
        self.dynamics = model.f
        self.C = np.array(model.C, dtype=float)

        # Integration step for the continuous plant (same as HybridSim: 1 ms / 1 kHz).
        self.dt_plant = 1e-3

        self.config_file = config_file

    def rk4_step(self, X, u_k) -> np.ndarray:
        """Advances the nonlinear plant state one integration step using classical RK4.

        Integrates  Ẋ = f(X, u)  over one ``dt_plant`` interval with the control
        input u_k held constant (zero-order hold within the substep).

        Args:
            X (np.ndarray): Current state vector [[r], [ṙ]], shape (2, 1).
            u_k (np.ndarray): Control input (servo command), shape (1, 1) or scalar.

        Returns:
            np.ndarray: Updated state vector [[r], [ṙ]], shape (2, 1).
        """
        u = float(np.squeeze(u_k))
        f = self.dynamics
        k1 = f(X, u)
        k2 = f(X + self.dt_plant * 0.5 * k1, u)
        k3 = f(X + 0.5 * self.dt_plant * k2, u)
        k4 = f(X + self.dt_plant * k3, u)
        return X + self.dt_plant / 6 * (k1 + 2*k2 + 2*k3 + k4)
